name: Publish Distribution to PyPI

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-publish-final-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --without docs tests

      - name: Build the package
        run: |
          poetry build

      - name: Publish to TestPyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish 
